---
apiVersion: v1
kind: ConfigMap
metadata:
  name: syncflaer
data:
  config.yml: |
    ---
    traefikInstances:
      - name: main
        url: https://traefik.example.com
        ignoredRules:
          - local.example.com
          - dev.example.com

    additionalRecords:
      - name: vpn.example.com
        ttl: 120

    cloudflare:
      email: mail@example.com
      zoneName: example.com
      deleteGrace: 5
      defaults:
        type: CNAME
        proxied: true
        ttl: 1
