---
apiVersion: v1
kind: ConfigMap
metadata:
  name: syncflaer
data:
  config.yml: |
    ---
    rootDomain: example.com

    ipProviders:
      - https://ifconfig.me/ip
      - https://ipecho.net/plain
      - https://myip.is/ip

    traefik:
      url: https://traefik.example.com
      ignoredRules:
        - local.example.com
        - dev.example.com

    additionalRecords:
      - name: vpn.example.com
        ttl: 120

    cloudflare:
      email: mail@example.com
      defaults:
        type: CNAME
        proxied: true
        ttl: 1
